---
- name: logical volume
  hosts: localhost
  tasks:
    - name: pv-create
      lvg:
        vg: vg1
        pvs: /dev/sdb
      tags: tag1

    - name: lv-create
      lvol:
        vg: vg1
        lv: lv1
        size: 100%FREE
      tags: tag2

    - name: Creating file system
      filesystem:
        fstype: xfs
        dev: /dev/vg1/lv1
      tags: tag3

    - name: Making directory
      file:
        path: /part
        state: directory
        mode: '0755'
      tags: tag4

    - name: Mounting the directory
      mount:
        path: /part
        src: /dev/vg1/lv1
        state: mounted
        fstype: xfs
      tags: tag5



