---
- name: For updating the system
  hosts: all
  tasks:
    - name: Update the server including kernel 
      yum:
        name: ' kernel '
        state: latest
      when:  ansible_kernel == "4.18.0-513.5.1.el8_9.x86_64"
